# Run configs
set ::env(PDK_ROOT) {/home/adming3/OpenLane/pdks}
set ::env(BASE_SDC_FILE) {/openlane/scripts/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CELLS_LEF) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD) {4}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_PERIOD) {10.0}
set ::env(CLOCK_PORT) {clk}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(CONFIGS) {/openlane/configuration/floorplan.tcl /openlane/configuration/cts.tcl /openlane/configuration/extraction.tcl /openlane/configuration/synthesis.tcl /openlane/configuration/checkers.tcl /openlane/configuration/lvs.tcl /openlane/configuration/placement.tcl /openlane/configuration/general.tcl /openlane/configuration/routing.tcl}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DECAP_CELL) {sky130_ef_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/openlane/designs/soc_core/config.tcl}
set ::env(DESIGN_DIR) {/openlane/designs/soc_core}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {soc_core}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {2}
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(ECO_STARTED) {0}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FILL_INSERTION) {1}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_MARGIN) {0}
set ::env(FP_CORE_UTIL) {45}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {3}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {16.65}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {153.18}
set ::env(FP_PDN_HSPACING) {1.7}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {16.32}
set ::env(FP_PDN_VPITCH) {153.6}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_PIN_ORDER_CFG) {/openlane/designs/soc_core/pin_order.cfg}
set ::env(FP_SIZING) {relative}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLB_RT_ADJUSTMENT) {0.3}
set ::env(GLB_RT_ALLOW_CONGESTION) {0}
set ::env(GLB_RT_ANT_ITERS) {3}
set ::env(GLB_RT_ESTIMATE_PARASITICS) {1}
set ::env(GLB_RT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GLB_RT_MACRO_EXTENSION) {0}
set ::env(GLB_RT_MAX_DIODE_INS_ITERS) {1}
set ::env(GLB_RT_OVERFLOW_ITERS) {50}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_PIN) {VGND}
set ::env(GPIO_PADS_LEF) { /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_VERILOG) { /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io.v /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io__gpiov2_pad_wrapped.v }
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_FASTEST) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_SLOWEST) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_TYPICAL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LOGS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(NETGEN_SETUP_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(PDK) {sky130A}
set ::env(PDKPATH) {/home/adming3/OpenLane/pdks/sky130A}
set ::env(PDN_CFG) {/openlane/scripts/openroad/pdn_cfg.tcl}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_LIB) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {20}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {20}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(PL_ROUTABILITY_DRIVEN) {0}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.5}
set ::env(PL_TIME_DRIVEN) {0}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_MISMATCHES) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.spef_extractor}
set ::env(RCX_RULES_MAX) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.spef_extractor}
set ::env(RCX_RULES_MIN) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.spef_extractor}
set ::env(REPORTS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports}
set ::env(RESULTS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {16}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35}
set ::env(RUN_KLAYOUT) {1}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {1}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_ROUTING_DETAILED) {1}
set ::env(RUN_SIMPLE_CTS) {0}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_TAG) {RUN_2022.04.28_12.53.35}
set ::env(SAVE_FINAL_VIEWS) {1}
set ::env(SPEF_EDGE_CAP_FACTOR) {1}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(SPEF_WIRE_MODEL) {L}
set ::env(START_TIME) {2022.04.28_12.53.35}
set ::env(STA_REPORT_POWER) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY_CDL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {1}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINITY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {5}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {0}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(SYNTH_TOP_LEVEL) {0}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TAP_DECAP_INSERTION) {1}
set ::env(TECH_LEF) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TEST_MISMATCHES) {all}
set ::env(TMP_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRISTATE_BUFFER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VDD_PIN) {VPWR}
set ::env(VERILOG_FILES) {./designs/soc_core/src/ibex_id_stage.v ./designs/soc_core/src/PWM32.v ./designs/soc_core/src/ibex_dummy_instr.v ./designs/soc_core/src/AHB_UART_MASTER.v ./designs/soc_core/src/AHBlite_bus0.v ./designs/soc_core/src/TIMER32.v ./designs/soc_core/src/ibex_compressed_decoder.v ./designs/soc_core/src/ibex_load_store_unit.v ./designs/soc_core/src/ibex_register_file_fpga.v ./designs/soc_core/src/AHB_Sec_ACC.v ./designs/soc_core/src/APB_I2C.v ./designs/soc_core/src/ibex_prefetch_buffer.v ./designs/soc_core/src/AHBlite_GPIO.v ./designs/soc_core/src/ibex_branch_predict.v ./designs/soc_core/src/ibex_multdiv_slow.v ./designs/soc_core/src/APB_SPI.v ./designs/soc_core/src/ibex_cs_registers.v ./designs/soc_core/src/soc_core.v ./designs/soc_core/src/ibex_register_file_latch.v ./designs/soc_core/src/ibex_wb_stage.v ./designs/soc_core/src/DFFRAMBB.v ./designs/soc_core/src/AHB_Sigmoid_ACC.v ./designs/soc_core/src/ibex_pkg.v ./designs/soc_core/src/AHBSRAM.v ./designs/soc_core/src/ibex_controller.v ./designs/soc_core/src/ibex_tracer_pkg.v ./designs/soc_core/src/prim_clock_gating.v ./designs/soc_core/src/GPIO.v ./designs/soc_core/src/APB_UART.v ./designs/soc_core/src/APB_PWM32.v ./designs/soc_core/src/AHB_SPM.v ./designs/soc_core/src/spi_master.v ./designs/soc_core/src/APB_bus0.v ./designs/soc_core/src/APB_TIMER32.v ./designs/soc_core/src/ibex_pmp.v ./designs/soc_core/src/ibex_decoder.v ./designs/soc_core/src/ibex_if_stage.v ./designs/soc_core/src/ibex_fetch_fifo.v ./designs/soc_core/src/AHB_MUX_2M1S.v ./designs/soc_core/src/ibex_counter.v ./designs/soc_core/src/AHBlite_sys_0.v ./designs/soc_core/src/ibex_wrapper.v ./designs/soc_core/src/WDT32.v ./designs/soc_core/src/AHBlite_db_reg.v ./designs/soc_core/src/AHB_tanh_ACC.v ./designs/soc_core/src/DMC_32x16HC.v ./designs/soc_core/src/i2c_master.v ./designs/soc_core/src/ibex_core_tracing.v ./designs/soc_core/src/ibex_ex_block.v ./designs/soc_core/src/APB_sys_0.v ./designs/soc_core/src/ibex_core.v ./designs/soc_core/src/AHB_ML_ACC.v ./designs/soc_core/src/ibex_multdiv_fast.v ./designs/soc_core/src/AHB_FLASH_WRITER.v ./designs/soc_core/src/APB_WDT32.v ./designs/soc_core/src/AHB_2_APB.v ./designs/soc_core/src/ibex_icache.v ./designs/soc_core/src/ibex_alu.v ./designs/soc_core/src/ibex_csr.v ./designs/soc_core/src/ibex_register_file_ff.v ./designs/soc_core/src/QSPI_XIP_CTRL.v}
set ::env(WIDEN_SITE) {1}
set ::env(WIDEN_SITE_IS_FACTOR) {1}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(cts_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/cts}
set ::env(cts_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/cts}
set ::env(cts_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/cts}
set ::env(cts_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts}
set ::env(eco_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/eco}
set ::env(eco_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/eco}
set ::env(eco_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/eco}
set ::env(eco_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/eco}
set ::env(floorplan_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/floorplan}
set ::env(floorplan_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/floorplan}
set ::env(floorplan_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/floorplan}
set ::env(floorplan_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan}
set ::env(placement_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/placement}
set ::env(placement_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/placement}
set ::env(placement_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/placement}
set ::env(placement_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/placement}
set ::env(routing_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/routing}
set ::env(routing_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/routing}
set ::env(routing_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing}
set ::env(routing_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing}
set ::env(signoff_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/signoff}
set ::env(signoff_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/signoff}
set ::env(signoff_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/signoff}
set ::env(signoff_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/signoff}
set ::env(synthesis_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/synthesis}
set ::env(synthesis_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis}
set ::env(synthesis_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/synthesis}
set ::env(synthesis_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(CURRENT_DEF) /openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-fill.def
set ::env(CURRENT_GUIDE) /openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/18-global.guide
set ::env(CURRENT_INDEX) 21
set ::env(CURRENT_NETLIST) /openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-global.v
set ::env(PREV_NETLIST) /openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing/soc_core.resized.v
set ::env(PDK_ROOT) {/home/adming3/OpenLane/pdks}
set ::env(BASE_SDC_FILE) {/openlane/scripts/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CELLS_LEF) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD) {4}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_NET) {clk}
set ::env(CLOCK_PERIOD) {10.0}
set ::env(CLOCK_PORT) {clk}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(CONFIGS) {/openlane/configuration/floorplan.tcl /openlane/configuration/cts.tcl /openlane/configuration/extraction.tcl /openlane/configuration/synthesis.tcl /openlane/configuration/checkers.tcl /openlane/configuration/lvs.tcl /openlane/configuration/placement.tcl /openlane/configuration/general.tcl /openlane/configuration/routing.tcl}
set ::env(CORE_AREA) {5.52 10.88 1231.42 1234.88}
set ::env(CORE_HEIGHT) {1224.0}
set ::env(CORE_WIDTH) {1225.9}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/placement/soc_core.def}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-fill.def}
set ::env(CURRENT_GUIDE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/18-global.guide}
set ::env(CURRENT_INDEX) {21}
set ::env(CURRENT_NETLIST) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-global.v}
set ::env(CURRENT_SDC) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/15-resizer_timing.sdc}
set ::env(CURRENT_STAGE) {routing}
set ::env(CURRENT_STEP) {routing}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DECAP_CELL) {sky130_ef_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/openlane/designs/soc_core/config.tcl}
set ::env(DESIGN_DIR) {/openlane/designs/soc_core}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {soc_core}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0.0 0.0 1237.4 1248.12}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {2}
set ::env(DISPLAY) {:0}
set ::env(DONT_USE_CELLS) {sky130_fd_sc_hd__a2111oi_0 sky130_fd_sc_hd__a21boi_0 sky130_fd_sc_hd__and2_0 sky130_fd_sc_hd__buf_16 sky130_fd_sc_hd__clkdlybuf4s15_1 sky130_fd_sc_hd__clkdlybuf4s18_1 sky130_fd_sc_hd__fa_4 sky130_fd_sc_hd__lpflow_bleeder_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_16 sky130_fd_sc_hd__lpflow_clkbufkapwr_2 sky130_fd_sc_hd__lpflow_clkbufkapwr_4 sky130_fd_sc_hd__lpflow_clkbufkapwr_8 sky130_fd_sc_hd__lpflow_clkinvkapwr_1 sky130_fd_sc_hd__lpflow_clkinvkapwr_16 sky130_fd_sc_hd__lpflow_clkinvkapwr_2 sky130_fd_sc_hd__lpflow_clkinvkapwr_4 sky130_fd_sc_hd__lpflow_clkinvkapwr_8 sky130_fd_sc_hd__lpflow_decapkapwr_12 sky130_fd_sc_hd__lpflow_decapkapwr_3 sky130_fd_sc_hd__lpflow_decapkapwr_4 sky130_fd_sc_hd__lpflow_decapkapwr_6 sky130_fd_sc_hd__lpflow_decapkapwr_8 sky130_fd_sc_hd__lpflow_inputiso0n_1 sky130_fd_sc_hd__lpflow_inputiso0p_1 sky130_fd_sc_hd__lpflow_inputiso1n_1 sky130_fd_sc_hd__lpflow_inputiso1p_1 sky130_fd_sc_hd__lpflow_inputisolatch_1 sky130_fd_sc_hd__lpflow_isobufsrc_1 sky130_fd_sc_hd__lpflow_isobufsrc_16 sky130_fd_sc_hd__lpflow_isobufsrc_2 sky130_fd_sc_hd__lpflow_isobufsrc_4 sky130_fd_sc_hd__lpflow_isobufsrc_8 sky130_fd_sc_hd__lpflow_isobufsrckapwr_16 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4 sky130_fd_sc_hd__mux4_4 sky130_fd_sc_hd__o21ai_0 sky130_fd_sc_hd__o311ai_0 sky130_fd_sc_hd__or2_0 sky130_fd_sc_hd__probe_p_8 sky130_fd_sc_hd__probec_p_8 sky130_fd_sc_hd__xor3_1 sky130_fd_sc_hd__xor3_2 sky130_fd_sc_hd__xor3_4 sky130_fd_sc_hd__xnor3_1 sky130_fd_sc_hd__xnor3_2 sky130_fd_sc_hd__xnor3_4 }
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(ECO_STARTED) {0}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FILL_INSERTION) {1}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_MARGIN) {0}
set ::env(FP_CORE_UTIL) {45}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {3}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {12.6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {12.6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {0}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {19.95}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {153.18}
set ::env(FP_PDN_HSPACING) {1.7}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_MACROS) {}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {19.62}
set ::env(FP_PDN_VPITCH) {153.6}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_PIN_ORDER_CFG) {/openlane/designs/soc_core/pin_order.cfg}
set ::env(FP_SIZING) {relative}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLB_RT_ADJUSTMENT) {0.3}
set ::env(GLB_RT_ALLOW_CONGESTION) {0}
set ::env(GLB_RT_ANT_ITERS) {3}
set ::env(GLB_RT_ESTIMATE_PARASITICS) {1}
set ::env(GLB_RT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GLB_RT_MACRO_EXTENSION) {0}
set ::env(GLB_RT_MAX_DIODE_INS_ITERS) {1}
set ::env(GLB_RT_OVERFLOW_ITERS) {50}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_NET) {VGND}
set ::env(GND_NETS) {VGND}
set ::env(GND_PIN) {VGND}
set ::env(GPIO_PADS_LEF) { /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_VERILOG) { /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io.v /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io__gpiov2_pad_wrapped.v }
set ::env(HOME) {/root}
set ::env(HOSTNAME) {csep072178g3}
set ::env(INPUT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-fill.def}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LANG) {en_US.UTF-8}
set ::env(LAST_TIMING_REPORT_TAG) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis/2-syn_sta}
set ::env(LC_ALL) {en_US.UTF-8}
set ::env(LC_CTYPE) {en_US.UTF-8}
set ::env(LD_LIBRARY_PATH) {/build//lib:/build//lib/Linux-x86_64:}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_CTS) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts/cts.lib}
set ::env(LIB_FASTEST) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_RESIZER_OPT) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/resizer_sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SLOWEST) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/trimmed.lib}
set ::env(LIB_SYNTH_COMPLETE) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SYNTH_COMPLETE_NO_PG) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/1-sky130_fd_sc_hd__tt_025C_1v80.no_pg.lib}
set ::env(LIB_SYNTH_MERGED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/merged.lib}
set ::env(LIB_TYPICAL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LOGS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(MANPATH) {/build//share/man:}
set ::env(MAX_METAL_LAYER) {6}
set ::env(MERGED_LEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(MERGED_LEF_MAX) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.max.lef}
set ::env(MERGED_LEF_MAX_UNPADDED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.max.lef}
set ::env(MERGED_LEF_MIN) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.min.lef}
set ::env(MERGED_LEF_MIN_UNPADDED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.min.lef}
set ::env(MERGED_LEF_ORIGINAL) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(MERGED_LEF_UNPADDED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.nom.lef}
set ::env(MERGED_LEF_UNPADDED_ORIGINAL) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.nom.lef}
set ::env(MERGED_LEF_UNPADDED_WIDENED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.nom.lef}
set ::env(MERGED_LEF_WIDENED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(NETGEN_SETUP_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OL_GIT_VERSION) {}
set ::env(OPENLANE_ROOT) {/openlane}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(OPENLANE_VERSION) {85b6ceca9e38a2187226457ad398f8da3353e8e5}
set ::env(OPENROAD) {/build/}
set ::env(OPENROAD_BIN) {openroad}
set ::env(PATH) {/openlane:/openlane/scripts:/build//bin:/build//bin/Linux-x86_64:/build//pdn/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
set ::env(PDK) {sky130A}
set ::env(PDKPATH) {/home/adming3/OpenLane/pdks/sky130A}
set ::env(PDK_ROOT) {/home/adming3/OpenLane/pdks}
set ::env(PDN_CFG) {/openlane/scripts/openroad/pdn_cfg.tcl}
set ::env(PGA_RPT_FILE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan/6-pdn.pga.rpt}
set ::env(PLACEMENT_CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan/6-pdn.def}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_INIT_COEFF) {0.00002}
set ::env(PL_IO_ITER) {5}
set ::env(PL_LIB) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {20}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {20}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(PL_ROUTABILITY_DRIVEN) {0}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.5}
set ::env(PL_TIME_DRIVEN) {0}
set ::env(PREV_NETLIST) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing/soc_core.resized.v}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(PWD) {/openlane}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_MISMATCHES) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.spef_extractor}
set ::env(RCX_RULES_MAX) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.spef_extractor}
set ::env(RCX_RULES_MIN) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.spef_extractor}
set ::env(REPORTS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports}
set ::env(RESULTS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {16}
set ::env(ROUTING_CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts/13-resizer_timing.def}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35}
set ::env(RUN_KLAYOUT) {1}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {1}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_ROUTING_DETAILED) {1}
set ::env(RUN_SIMPLE_CTS) {0}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_STANDALONE) {1}
set ::env(RUN_TAG) {RUN_2022.04.28_12.53.35}
set ::env(SAVE_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing/soc_core.def}
set ::env(SAVE_FINAL_VIEWS) {1}
set ::env(SAVE_GUIDE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/18-global.guide}
set ::env(SAVE_NETLIST) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-global.v}
set ::env(SAVE_SDC) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/15-resizer_timing.sdc}
set ::env(SCRIPTS_DIR) {/openlane/scripts}
set ::env(SHLVL) {2}
set ::env(SPEF_EDGE_CAP_FACTOR) {1}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(SPEF_WIRE_MODEL) {L}
set ::env(START_TIME) {2022.04.28_12.53.35}
set ::env(STA_LEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(STA_PRE_CTS) {1}
set ::env(STA_REPORT_POWER) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_CDL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {1}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINITY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {5}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_OPT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {0}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(SYNTH_TOP_LEVEL) {0}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TAP_DECAP_INSERTION) {1}
set ::env(TECH_LEF) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_METAL_LAYERS) {li1  met1  met2  met3  met4  met5}
set ::env(TERM) {xterm}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TEST_MISMATCHES) {all}
set ::env(TMP_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRACKS_INFO_FILE_PROCESSED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/config.tracks}
set ::env(TRISTATE_BUFFER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(TRITONROUTE_FILE_PREFIX) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/detailed}
set ::env(TRITONROUTE_RPT_PREFIX) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/routing/detailed}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VCHECK_OUTPUT) {}
set ::env(VDD_NET) {VPWR}
set ::env(VDD_NETS) {VPWR}
set ::env(VDD_PIN) {VPWR}
set ::env(VERILOG_FILES) {./designs/soc_core/src/ibex_id_stage.v ./designs/soc_core/src/PWM32.v ./designs/soc_core/src/ibex_dummy_instr.v ./designs/soc_core/src/AHB_UART_MASTER.v ./designs/soc_core/src/AHBlite_bus0.v ./designs/soc_core/src/TIMER32.v ./designs/soc_core/src/ibex_compressed_decoder.v ./designs/soc_core/src/ibex_load_store_unit.v ./designs/soc_core/src/ibex_register_file_fpga.v ./designs/soc_core/src/AHB_Sec_ACC.v ./designs/soc_core/src/APB_I2C.v ./designs/soc_core/src/ibex_prefetch_buffer.v ./designs/soc_core/src/AHBlite_GPIO.v ./designs/soc_core/src/ibex_branch_predict.v ./designs/soc_core/src/ibex_multdiv_slow.v ./designs/soc_core/src/APB_SPI.v ./designs/soc_core/src/ibex_cs_registers.v ./designs/soc_core/src/soc_core.v ./designs/soc_core/src/ibex_register_file_latch.v ./designs/soc_core/src/ibex_wb_stage.v ./designs/soc_core/src/DFFRAMBB.v ./designs/soc_core/src/AHB_Sigmoid_ACC.v ./designs/soc_core/src/ibex_pkg.v ./designs/soc_core/src/AHBSRAM.v ./designs/soc_core/src/ibex_controller.v ./designs/soc_core/src/ibex_tracer_pkg.v ./designs/soc_core/src/prim_clock_gating.v ./designs/soc_core/src/GPIO.v ./designs/soc_core/src/APB_UART.v ./designs/soc_core/src/APB_PWM32.v ./designs/soc_core/src/AHB_SPM.v ./designs/soc_core/src/spi_master.v ./designs/soc_core/src/APB_bus0.v ./designs/soc_core/src/APB_TIMER32.v ./designs/soc_core/src/ibex_pmp.v ./designs/soc_core/src/ibex_decoder.v ./designs/soc_core/src/ibex_if_stage.v ./designs/soc_core/src/ibex_fetch_fifo.v ./designs/soc_core/src/AHB_MUX_2M1S.v ./designs/soc_core/src/ibex_counter.v ./designs/soc_core/src/AHBlite_sys_0.v ./designs/soc_core/src/ibex_wrapper.v ./designs/soc_core/src/WDT32.v ./designs/soc_core/src/AHBlite_db_reg.v ./designs/soc_core/src/AHB_tanh_ACC.v ./designs/soc_core/src/DMC_32x16HC.v ./designs/soc_core/src/i2c_master.v ./designs/soc_core/src/ibex_core_tracing.v ./designs/soc_core/src/ibex_ex_block.v ./designs/soc_core/src/APB_sys_0.v ./designs/soc_core/src/ibex_core.v ./designs/soc_core/src/AHB_ML_ACC.v ./designs/soc_core/src/ibex_multdiv_fast.v ./designs/soc_core/src/AHB_FLASH_WRITER.v ./designs/soc_core/src/APB_WDT32.v ./designs/soc_core/src/AHB_2_APB.v ./designs/soc_core/src/ibex_icache.v ./designs/soc_core/src/ibex_alu.v ./designs/soc_core/src/ibex_csr.v ./designs/soc_core/src/ibex_register_file_ff.v ./designs/soc_core/src/QSPI_XIP_CTRL.v}
set ::env(WIDEN_SITE) {1}
set ::env(WIDEN_SITE_IS_FACTOR) {1}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(_) {./flow.tcl}
set ::env(cts_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/cts}
set ::env(cts_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/cts}
set ::env(cts_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/cts}
set ::env(cts_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts}
set ::env(eco_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/eco}
set ::env(eco_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/eco}
set ::env(eco_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/eco}
set ::env(eco_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/eco}
set ::env(floorplan_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/floorplan}
set ::env(floorplan_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/floorplan}
set ::env(floorplan_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/floorplan}
set ::env(floorplan_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan}
set ::env(fp_report_prefix) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/floorplan/3-initial_fp}
set ::env(placement_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/placement}
set ::env(placement_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/placement}
set ::env(placement_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/placement}
set ::env(placement_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/placement}
set ::env(routing_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/routing}
set ::env(routing_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/routing}
set ::env(routing_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing}
set ::env(routing_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing}
set ::env(signoff_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/signoff}
set ::env(signoff_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/signoff}
set ::env(signoff_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/signoff}
set ::env(signoff_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/signoff}
set ::env(synth_report_prefix) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis/1-synthesis}
set ::env(synthesis_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/synthesis}
set ::env(synthesis_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis}
set ::env(synthesis_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/synthesis}
set ::env(synthesis_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis}
set ::env(timer_start) {1651150415}
set ::env(PDK_ROOT) {/home/adming3/OpenLane/pdks}
set ::env(BASE_SDC_FILE) {/openlane/scripts/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CELLS_LEF) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD) {4}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_NET) {clk}
set ::env(CLOCK_PERIOD) {10.0}
set ::env(CLOCK_PORT) {clk}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(CONFIGS) {/openlane/configuration/floorplan.tcl /openlane/configuration/cts.tcl /openlane/configuration/extraction.tcl /openlane/configuration/synthesis.tcl /openlane/configuration/checkers.tcl /openlane/configuration/lvs.tcl /openlane/configuration/placement.tcl /openlane/configuration/general.tcl /openlane/configuration/routing.tcl}
set ::env(CORE_AREA) {5.52 10.88 1231.42 1234.88}
set ::env(CORE_HEIGHT) {1224.0}
set ::env(CORE_WIDTH) {1225.9}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/placement/soc_core.def}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-fill.def}
set ::env(CURRENT_GUIDE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/18-global.guide}
set ::env(CURRENT_INDEX) {21}
set ::env(CURRENT_NETLIST) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-global.v}
set ::env(CURRENT_SDC) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/15-resizer_timing.sdc}
set ::env(CURRENT_STAGE) {routing}
set ::env(CURRENT_STEP) {routing}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DECAP_CELL) {sky130_ef_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/openlane/designs/soc_core/config.tcl}
set ::env(DESIGN_DIR) {/openlane/designs/soc_core}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {soc_core}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0.0 0.0 1237.4 1248.12}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {2}
set ::env(DISPLAY) {:0}
set ::env(DONT_USE_CELLS) {sky130_fd_sc_hd__a2111oi_0 sky130_fd_sc_hd__a21boi_0 sky130_fd_sc_hd__and2_0 sky130_fd_sc_hd__buf_16 sky130_fd_sc_hd__clkdlybuf4s15_1 sky130_fd_sc_hd__clkdlybuf4s18_1 sky130_fd_sc_hd__fa_4 sky130_fd_sc_hd__lpflow_bleeder_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_16 sky130_fd_sc_hd__lpflow_clkbufkapwr_2 sky130_fd_sc_hd__lpflow_clkbufkapwr_4 sky130_fd_sc_hd__lpflow_clkbufkapwr_8 sky130_fd_sc_hd__lpflow_clkinvkapwr_1 sky130_fd_sc_hd__lpflow_clkinvkapwr_16 sky130_fd_sc_hd__lpflow_clkinvkapwr_2 sky130_fd_sc_hd__lpflow_clkinvkapwr_4 sky130_fd_sc_hd__lpflow_clkinvkapwr_8 sky130_fd_sc_hd__lpflow_decapkapwr_12 sky130_fd_sc_hd__lpflow_decapkapwr_3 sky130_fd_sc_hd__lpflow_decapkapwr_4 sky130_fd_sc_hd__lpflow_decapkapwr_6 sky130_fd_sc_hd__lpflow_decapkapwr_8 sky130_fd_sc_hd__lpflow_inputiso0n_1 sky130_fd_sc_hd__lpflow_inputiso0p_1 sky130_fd_sc_hd__lpflow_inputiso1n_1 sky130_fd_sc_hd__lpflow_inputiso1p_1 sky130_fd_sc_hd__lpflow_inputisolatch_1 sky130_fd_sc_hd__lpflow_isobufsrc_1 sky130_fd_sc_hd__lpflow_isobufsrc_16 sky130_fd_sc_hd__lpflow_isobufsrc_2 sky130_fd_sc_hd__lpflow_isobufsrc_4 sky130_fd_sc_hd__lpflow_isobufsrc_8 sky130_fd_sc_hd__lpflow_isobufsrckapwr_16 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4 sky130_fd_sc_hd__mux4_4 sky130_fd_sc_hd__o21ai_0 sky130_fd_sc_hd__o311ai_0 sky130_fd_sc_hd__or2_0 sky130_fd_sc_hd__probe_p_8 sky130_fd_sc_hd__probec_p_8 sky130_fd_sc_hd__xor3_1 sky130_fd_sc_hd__xor3_2 sky130_fd_sc_hd__xor3_4 sky130_fd_sc_hd__xnor3_1 sky130_fd_sc_hd__xnor3_2 sky130_fd_sc_hd__xnor3_4 }
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(ECO_STARTED) {0}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FILL_INSERTION) {1}
set ::env(FLOW_FAILED) {1}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_MARGIN) {0}
set ::env(FP_CORE_UTIL) {45}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {3}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {12.6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {12.6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {0}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {19.95}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {153.18}
set ::env(FP_PDN_HSPACING) {1.7}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_MACROS) {}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {19.62}
set ::env(FP_PDN_VPITCH) {153.6}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_PIN_ORDER_CFG) {/openlane/designs/soc_core/pin_order.cfg}
set ::env(FP_SIZING) {relative}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLB_RT_ADJUSTMENT) {0.3}
set ::env(GLB_RT_ALLOW_CONGESTION) {0}
set ::env(GLB_RT_ANT_ITERS) {3}
set ::env(GLB_RT_ESTIMATE_PARASITICS) {1}
set ::env(GLB_RT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GLB_RT_MACRO_EXTENSION) {0}
set ::env(GLB_RT_MAX_DIODE_INS_ITERS) {1}
set ::env(GLB_RT_OVERFLOW_ITERS) {50}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_NET) {VGND}
set ::env(GND_NETS) {VGND}
set ::env(GND_PIN) {VGND}
set ::env(GPIO_PADS_LEF) { /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_VERILOG) { /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io.v /home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io__gpiov2_pad_wrapped.v }
set ::env(HOME) {/root}
set ::env(HOSTNAME) {csep072178g3}
set ::env(INPUT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-fill.def}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/klayout/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LANG) {en_US.UTF-8}
set ::env(LAST_TIMING_REPORT_TAG) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis/2-syn_sta}
set ::env(LC_ALL) {en_US.UTF-8}
set ::env(LC_CTYPE) {en_US.UTF-8}
set ::env(LD_LIBRARY_PATH) {/build//lib:/build//lib/Linux-x86_64:}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_CTS) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts/cts.lib}
set ::env(LIB_FASTEST) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_RESIZER_OPT) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/resizer_sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SLOWEST) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/trimmed.lib}
set ::env(LIB_SYNTH_COMPLETE) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SYNTH_COMPLETE_NO_PG) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/1-sky130_fd_sc_hd__tt_025C_1v80.no_pg.lib}
set ::env(LIB_SYNTH_MERGED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis/merged.lib}
set ::env(LIB_TYPICAL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LOGS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(MANPATH) {/build//share/man:}
set ::env(MAX_METAL_LAYER) {6}
set ::env(MERGED_LEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(MERGED_LEF_MAX) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.max.lef}
set ::env(MERGED_LEF_MAX_UNPADDED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.max.lef}
set ::env(MERGED_LEF_MIN) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.min.lef}
set ::env(MERGED_LEF_MIN_UNPADDED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.min.lef}
set ::env(MERGED_LEF_ORIGINAL) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(MERGED_LEF_UNPADDED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.nom.lef}
set ::env(MERGED_LEF_UNPADDED_ORIGINAL) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.nom.lef}
set ::env(MERGED_LEF_UNPADDED_WIDENED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.unpadded.nom.lef}
set ::env(MERGED_LEF_WIDENED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(NETGEN_SETUP_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OL_GIT_VERSION) {}
set ::env(OPENLANE_ROOT) {/openlane}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(OPENLANE_VERSION) {85b6ceca9e38a2187226457ad398f8da3353e8e5}
set ::env(OPENROAD) {/build/}
set ::env(OPENROAD_BIN) {openroad}
set ::env(PATH) {/openlane:/openlane/scripts:/build//bin:/build//bin/Linux-x86_64:/build//pdn/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
set ::env(PDK) {sky130A}
set ::env(PDKPATH) {/home/adming3/OpenLane/pdks/sky130A}
set ::env(PDK_ROOT) {/home/adming3/OpenLane/pdks}
set ::env(PDN_CFG) {/openlane/scripts/openroad/pdn_cfg.tcl}
set ::env(PGA_RPT_FILE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan/6-pdn.pga.rpt}
set ::env(PLACEMENT_CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan/6-pdn.def}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_INIT_COEFF) {0.00002}
set ::env(PL_IO_ITER) {5}
set ::env(PL_LIB) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {20}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {20}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(PL_ROUTABILITY_DRIVEN) {0}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.5}
set ::env(PL_TIME_DRIVEN) {0}
set ::env(PREV_NETLIST) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing/soc_core.resized.v}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(PWD) {/openlane}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_MISMATCHES) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.spef_extractor}
set ::env(RCX_RULES_MAX) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.spef_extractor}
set ::env(RCX_RULES_MIN) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.spef_extractor}
set ::env(REPORTS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports}
set ::env(RESULTS_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {16}
set ::env(ROUTING_CURRENT_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts/13-resizer_timing.def}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35}
set ::env(RUN_KLAYOUT) {1}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {1}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_ROUTING_DETAILED) {1}
set ::env(RUN_SIMPLE_CTS) {0}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_STANDALONE) {1}
set ::env(RUN_TAG) {RUN_2022.04.28_12.53.35}
set ::env(SAVE_DEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing/soc_core.def}
set ::env(SAVE_FINAL_VIEWS) {1}
set ::env(SAVE_GUIDE) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/18-global.guide}
set ::env(SAVE_NETLIST) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/19-global.v}
set ::env(SAVE_SDC) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/15-resizer_timing.sdc}
set ::env(SCRIPTS_DIR) {/openlane/scripts}
set ::env(SHLVL) {2}
set ::env(SPEF_EDGE_CAP_FACTOR) {1}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(SPEF_WIRE_MODEL) {L}
set ::env(START_TIME) {2022.04.28_12.53.35}
set ::env(STA_LEF) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/merged.nom.lef}
set ::env(STA_PRE_CTS) {1}
set ::env(STA_REPORT_POWER) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_CDL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {1}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINITY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {5}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_OPT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {0}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(SYNTH_TOP_LEVEL) {0}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TAP_DECAP_INSERTION) {1}
set ::env(TECH_LEF) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/home/adming3/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_METAL_LAYERS) {li1  met1  met2  met3  met4  met5}
set ::env(TERM) {xterm}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TEST_MISMATCHES) {all}
set ::env(TMP_DIR) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRACKS_INFO_FILE_PROCESSED) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/config.tracks}
set ::env(TRISTATE_BUFFER_MAP) {/home/adming3/OpenLane/pdks/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(TRITONROUTE_FILE_PREFIX) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing/detailed}
set ::env(TRITONROUTE_RPT_PREFIX) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/routing/detailed}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VCHECK_OUTPUT) {}
set ::env(VDD_NET) {VPWR}
set ::env(VDD_NETS) {VPWR}
set ::env(VDD_PIN) {VPWR}
set ::env(VERILOG_FILES) {./designs/soc_core/src/ibex_id_stage.v ./designs/soc_core/src/PWM32.v ./designs/soc_core/src/ibex_dummy_instr.v ./designs/soc_core/src/AHB_UART_MASTER.v ./designs/soc_core/src/AHBlite_bus0.v ./designs/soc_core/src/TIMER32.v ./designs/soc_core/src/ibex_compressed_decoder.v ./designs/soc_core/src/ibex_load_store_unit.v ./designs/soc_core/src/ibex_register_file_fpga.v ./designs/soc_core/src/AHB_Sec_ACC.v ./designs/soc_core/src/APB_I2C.v ./designs/soc_core/src/ibex_prefetch_buffer.v ./designs/soc_core/src/AHBlite_GPIO.v ./designs/soc_core/src/ibex_branch_predict.v ./designs/soc_core/src/ibex_multdiv_slow.v ./designs/soc_core/src/APB_SPI.v ./designs/soc_core/src/ibex_cs_registers.v ./designs/soc_core/src/soc_core.v ./designs/soc_core/src/ibex_register_file_latch.v ./designs/soc_core/src/ibex_wb_stage.v ./designs/soc_core/src/DFFRAMBB.v ./designs/soc_core/src/AHB_Sigmoid_ACC.v ./designs/soc_core/src/ibex_pkg.v ./designs/soc_core/src/AHBSRAM.v ./designs/soc_core/src/ibex_controller.v ./designs/soc_core/src/ibex_tracer_pkg.v ./designs/soc_core/src/prim_clock_gating.v ./designs/soc_core/src/GPIO.v ./designs/soc_core/src/APB_UART.v ./designs/soc_core/src/APB_PWM32.v ./designs/soc_core/src/AHB_SPM.v ./designs/soc_core/src/spi_master.v ./designs/soc_core/src/APB_bus0.v ./designs/soc_core/src/APB_TIMER32.v ./designs/soc_core/src/ibex_pmp.v ./designs/soc_core/src/ibex_decoder.v ./designs/soc_core/src/ibex_if_stage.v ./designs/soc_core/src/ibex_fetch_fifo.v ./designs/soc_core/src/AHB_MUX_2M1S.v ./designs/soc_core/src/ibex_counter.v ./designs/soc_core/src/AHBlite_sys_0.v ./designs/soc_core/src/ibex_wrapper.v ./designs/soc_core/src/WDT32.v ./designs/soc_core/src/AHBlite_db_reg.v ./designs/soc_core/src/AHB_tanh_ACC.v ./designs/soc_core/src/DMC_32x16HC.v ./designs/soc_core/src/i2c_master.v ./designs/soc_core/src/ibex_core_tracing.v ./designs/soc_core/src/ibex_ex_block.v ./designs/soc_core/src/APB_sys_0.v ./designs/soc_core/src/ibex_core.v ./designs/soc_core/src/AHB_ML_ACC.v ./designs/soc_core/src/ibex_multdiv_fast.v ./designs/soc_core/src/AHB_FLASH_WRITER.v ./designs/soc_core/src/APB_WDT32.v ./designs/soc_core/src/AHB_2_APB.v ./designs/soc_core/src/ibex_icache.v ./designs/soc_core/src/ibex_alu.v ./designs/soc_core/src/ibex_csr.v ./designs/soc_core/src/ibex_register_file_ff.v ./designs/soc_core/src/QSPI_XIP_CTRL.v}
set ::env(WIDEN_SITE) {1}
set ::env(WIDEN_SITE_IS_FACTOR) {1}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(_) {./flow.tcl}
set ::env(cts_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/cts}
set ::env(cts_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/cts}
set ::env(cts_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/cts}
set ::env(cts_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/cts}
set ::env(eco_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/eco}
set ::env(eco_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/eco}
set ::env(eco_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/eco}
set ::env(eco_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/eco}
set ::env(floorplan_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/floorplan}
set ::env(floorplan_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/floorplan}
set ::env(floorplan_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/floorplan}
set ::env(floorplan_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/floorplan}
set ::env(fp_report_prefix) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/floorplan/3-initial_fp}
set ::env(placement_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/placement}
set ::env(placement_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/placement}
set ::env(placement_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/placement}
set ::env(placement_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/placement}
set ::env(routing_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/routing}
set ::env(routing_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/routing}
set ::env(routing_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/routing}
set ::env(routing_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/routing}
set ::env(signoff_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/signoff}
set ::env(signoff_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/signoff}
set ::env(signoff_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/signoff}
set ::env(signoff_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/signoff}
set ::env(synth_report_prefix) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis/1-synthesis}
set ::env(synthesis_logs) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/logs/synthesis}
set ::env(synthesis_reports) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/reports/synthesis}
set ::env(synthesis_results) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/results/synthesis}
set ::env(synthesis_tmpfiles) {/openlane/designs/soc_core/runs/RUN_2022.04.28_12.53.35/tmp/synthesis}
set ::env(timer_end) {1651239374}
set ::env(timer_start) {1651150415}
